import {
  autoGeneratedHashKey,
  rangeKey,
  table,
  attribute,
} from '@aws/dynamodb-data-mapper-annotations';

@table('guesses')
export class Guess {
  @autoGeneratedHashKey()
  id: string;

  @rangeKey()
  createdAt: Date;

  @rangeKey()
  updatedAt: Date;

  @attribute()
  userId: string;

  @attribute()
  guess: number;

  @attribute()
  btcPrice: number;
}
