import {
  autoGeneratedHashKey,
  rangeKey,
  table,
  attribute,
} from '@aws/dynamodb-data-mapper-annotations';

@table('users')
export class User {
  @autoGeneratedHashKey()
  id: string;

  @rangeKey()
  createdAt: Date;

  @rangeKey()
  updatedAt: Date;

  @attribute()
  email: string;

  @attribute()
  state: UserState;

  @attribute()
  score: number;

  @attribute()
  latestGuessId: string;
}

export enum UserState {
  CAN_GUESS,
  GUESSING,
}
